name: base
channels:
  - defaults
dependencies:
  - _anaconda_depends=2020.07
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.7.2
  - anaconda-navigator=1.9.12
  - anaconda-project=0.9.1
  - anyio=2.2.0
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - asn1crypto=1.4.0
  - astroid=2.4.2
  - astropy=4.0.1.post1
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - autopep8=1.5.6
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - backports.shutil_get_terminal_size=1.0.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - beautifulsoup4=4.9.3
  - bitarray=1.9.2
  - bkcharts=0.2
  - blas=1.0
  - bleach=3.3.0
  - blosc=1.21.0
  - bokeh=2.1.1
  - boto=2.49.0
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.4.13
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - clyent=1.2.2
  - colorama=0.4.4
  - conda=4.10.1
  - conda-build=3.18.11
  - conda-env=2.6.0
  - conda-package-handling=1.7.3
  - conda-verify=3.4.2
  - contextlib2=0.6.0.post1
  - cryptography=3.4.7
  - curl=7.71.1
  - cycler=0.10.0
  - cython=0.29.23
  - cytoolz=0.11.0
  - dask=2.20.0
  - dask-core=2.20.0
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - distributed=2.30.1
  - docutils=0.17
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.3.0
  - fastcache=1.1.0
  - filelock=3.0.12
  - flake8=3.9.0
  - flask=1.1.2
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - fsspec=0.9.0
  - future=0.18.2
  - get_terminal_size=1.0.0
  - gevent=21.1.2
  - glib=2.68.1
  - glob2=0.7
  - gmp=6.2.1
  - gmpy2=2.0.8
  - graphite2=1.3.14
  - greenlet=1.0.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - harfbuzz=2.8.0
  - hdf5=1.10.4
  - heapdict=1.0.1
  - html5lib=1.1
  - icu=58.2
  - idna=2.10
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - iniconfig=1.1.1
  - intel-openmp=2020.2
  - intervaltree=3.1.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.17.1
  - jeepney=0.6.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=3.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.4.0
  - jupyterlab_widgets=1.0.0
  - keyring=22.3.0
  - kiwisolver=1.3.1
  - krb5=1.18.2
  - lazy-object-proxy=1.4.3
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - libarchive=3.4.2
  - libcurl=7.71.1
  - libedit=3.1.20210216
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - liblief=0.10.1
  - libllvm9=9.0.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.10
  - libxslt=1.1.34
  - llvmlite=0.33.0
  - locket=0.2.1
  - lxml=4.6.3
  - lz4-c=1.9.3
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - mock=4.0.3
  - more-itertools=8.7.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - msgpack-python=1.0.2
  - multipledispatch=0.6.0
  - navigator-updater=0.2.1
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.5.1
  - nltk=3.6.1
  - nose=1.3.7
  - notebook=6.3.0
  - numba=0.50.1
  - numexpr=2.7.1
  - numpy-base=1.18.5
  - numpydoc=1.1.0
  - olefile=0.46
  - openpyxl=3.0.7
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.0.5
  - pandoc=2.12
  - pandocfilters=1.4.3
  - pango=1.45.3
  - parso=0.7.0
  - partd=1.2.0
  - patchelf=0.12
  - path=15.1.2
  - path.py=12.5.0
  - pathlib2=2.3.5
  - pathtools=0.1.2
  - patsy=0.5.1
  - pcre=8.44
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=20.1.1
  - pixman=0.40.0
  - pkginfo=1.7.0
  - pluggy=0.13.1
  - ply=3.11
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py=1.10.0
  - py-lief=0.10.1
  - pycodestyle=2.6.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycurl=7.43.0.6
  - pydocstyle=6.0.0
  - pyflakes=2.2.0
  - pygments=2.8.1
  - pylint=2.5.3
  - pyodbc=4.0.30
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.2.3
  - python=3.8.3
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.3.4
  - python-language-server=0.34.1
  - python-libarchive-c=2.9
  - pytz=2021.1
  - pywavelets=1.1.1
  - pyxdg=0.27
  - pyyaml=5.4.1
  - pyzmq=20.0.0
  - qdarkstyle=3.0.2
  - qt=5.9.7
  - qtawesome=1.0.2
  - qtconsole=5.0.3
  - qtpy=1.9.0
  - readline=8.1
  - regex=2021.4.4
  - requests=2.25.1
  - ripgrep=12.1.1
  - rope=0.18.0
  - rtree=0.9.7
  - ruamel_yaml=0.15.100
  - scikit-image=0.16.2
  - scikit-learn=0.23.1
  - seaborn=0.10.1
  - secretstorage=3.3.1
  - send2trash=1.5.0
  - setuptools=52.0.0
  - simplegeneric=0.8.1
  - singledispatch=3.6.1
  - sip=4.19.13
  - six=1.15.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - snowballstemmer=2.1.0
  - sortedcollections=2.1.0
  - sortedcontainers=2.3.0
  - soupsieve=2.2.1
  - sphinx=3.1.2
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sphinxcontrib-websupport=1.2.4
  - spyder=4.1.4
  - spyder-kernels=1.9.4
  - sqlalchemy=1.4.7
  - sqlite=3.35.4
  - statsmodels=0.11.1
  - sympy=1.8
  - tbb=2020.3
  - tblib=1.7.0
  - terminado=0.9.4
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.59.0
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - ujson=1.35
  - unicodecsv=0.14.1
  - unixodbc=2.3.9
  - urllib3=1.26.4
  - watchdog=1.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - widgetsnbextension=3.5.1
  - wurlitzer=2.1.0
  - xlrd=2.0.1
  - xlsxwriter=1.3.8
  - xlwt=1.3.0
  - xmltodict=0.12.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zict=2.0.0
  - zipp=3.4.1
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.3.0
  - zstd=1.4.5
  - pip:
    - absl-py==0.11.0
    - appdirs==1.4.4
    - asgiref==3.3.1
    - astunparse==1.6.3
    - cachetools==4.1.1
    - django==3.1.7
    - dm-tree==0.1.5
    - evidential-deep-learning==0.4.0
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - intel-tensorflow-avx512==2.3.0
    - keras==2.4.3
    - keras-preprocessing==1.1.2
    - markdown==3.3.3
    - meshio==4.3.11
    - numpy==1.19.5
    - oauthlib==3.1.0
    - opencv-python==4.5.1.48
    - opt-einsum==3.3.0
    - plotly==4.14.3
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pysqlite3==0.4.6
    - pyvista==0.29.0
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rsa==4.6
    - scipy==1.4.1
    - scooby==0.5.6
    - sqlparse==0.4.1
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.4.1
    - tensorflow-estimator==2.4.0
    - tensorflow-probability==0.12.1
    - termcolor==1.1.0
    - torch==1.7.1+cu110
    - torchaudio==0.7.2
    - torchvision==0.8.2+cu110
    - transforms3d==0.3.1
    - vtk==9.0.1
    - websocket==0.2.1
    - websockets==9.0.1
    - wheel==0.36.2
    - wrapt==1.12.1
